mirror:github:
    stage: deploy
    image: ubuntu:latest
    script:
    - "apt-get update"
    - "apt-get install git -y"
    - "git clone https://code.ini.uzh.ch/orichter/ci-mirror-tools.git deploy_github"
    - "cd deploy_github"
    - "bash mirror.sh"